.TH "Receiver_LoRa/miscRx.h" 3 "Fri Nov 6 2020" "Projet Lora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Receiver_LoRa/miscRx.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRx\fP"
.br
.RI "Structure représentant un noeud enregistré "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBupdate\fP (byte *buffer)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void update (byte * buffer)"

.PP
Definition at line 21 of file miscRx\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Projet Lora from the source code\&.
