.TH "Sender_LoRa/miscTx.h" 3 "Fri Nov 6 2020" "Projet Lora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sender_LoRa/miscTx.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBalarme\fP ()"
.br
.RI "Signal d'alerte audio\&. "
.ti -1c
.RI "void \fBafficheMesure\fP ()"
.br
.RI "Fonction d'affichage des dernières mesures\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void afficheMesure ()"

.PP
Fonction d'affichage des dernières mesures\&. 
.PP
Definition at line 42 of file miscTx\&.h\&.
.SS "void alarme ()"

.PP
Signal d'alerte audio\&. Antoine PLANTIER 
.SH "Projet Lora"
.PP
Fonctions diverses pour Tx
.PP
[long description] 
.PP
Definition at line 14 of file miscTx\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Projet Lora from the source code\&.
