.TH "Rx" 3 "Fri Nov 6 2020" "Projet Lora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rx \- Structure représentant un noeud enregistré  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <miscRx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBactif\fP"
.br
.ti -1c
.RI "int \fBreportCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure représentant un noeud enregistré 

Antoine PLANTIER 
.SH "Projet Lora"
.PP
Fonctions diverses pour \fBRx\fP
.PP
Actif : Savoir si le noeud est actif , usage futur pour permettre le remplacement d'un noeud inactif par un autre 
.PP
Definition at line 14 of file miscRx\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Rx::actif"

.PP
Definition at line 16 of file miscRx\&.h\&.
.SS "int Rx::reportCount"

.PP
Definition at line 17 of file miscRx\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet Lora from the source code\&.
